// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Asset_Tracking_System.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20260717125508_AddTurkeyMobileSeed")]
    partial class AddTurkeyMobileSeed
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Asset", b =>
                {
                    b.Property<int>("AssetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("AssetId"));

                    b.Property<string>("AssetType")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("varchar(13)");

                    b.Property<string>("AssignedEmployee")
                        .HasColumnType("longtext");

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Office")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double>("PriceUSD")
                        .HasColumnType("double");

                    b.Property<DateTime>("PurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("SerialNumber")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("WarrantyExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("AssetId");

                    b.ToTable("Assets");

                    b.HasDiscriminator<string>("AssetType").HasValue("Asset");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("Computer", b =>
                {
                    b.HasBaseType("Asset");

                    b.HasDiscriminator().HasValue("Computer");

                    b.HasData(
                        new
                        {
                            AssetId = 1001,
                            AssignedEmployee = "Anna",
                            Brand = "Dell",
                            Currency = "SEK",
                            Model = "Latitude 5440",
                            Office = "Sweden",
                            PriceUSD = 1200.0,
                            PurchaseDate = new DateTime(2024, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "DELL001",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2027, 1, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssetId = 1002,
                            AssignedEmployee = "John",
                            Brand = "Apple",
                            Currency = "USD",
                            Model = "MacBook Pro M3",
                            Office = "USA",
                            PriceUSD = 2500.0,
                            PurchaseDate = new DateTime(2023, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "APPLE001",
                            Type = "Computer",
                            WarrantyExpirationDate = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("MobilePhone", b =>
                {
                    b.HasBaseType("Asset");

                    b.HasDiscriminator().HasValue("MobilePhone");

                    b.HasData(
                        new
                        {
                            AssetId = 1003,
                            AssignedEmployee = "Maria",
                            Brand = "Samsung",
                            Currency = "EUR",
                            Model = "Galaxy S24",
                            Office = "Germany",
                            PriceUSD = 900.0,
                            PurchaseDate = new DateTime(2025, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "SAM001",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2027, 2, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            AssetId = 1004,
                            AssignedEmployee = "Ahmet",
                            Brand = "Apple",
                            Currency = "TRY",
                            Model = "iPhone 15",
                            Office = "Turkey",
                            PriceUSD = 1200.0,
                            PurchaseDate = new DateTime(2025, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            SerialNumber = "APPLE002",
                            Type = "Mobile",
                            WarrantyExpirationDate = new DateTime(2028, 9, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
